### ISSUE TITLE
Redesign the background of the website

### ISSUE THREAD

**Issue by Mayank1170** [FOSS-Community/progress-tracker#329]
## Overview
Redesign the background of the website.
## Description

Redesign the background of the website, it must be attractive and responsive. Make sure to use perfect combination of colors.

## Expected outcomes

An attractive and simple and responsive background which is more user friendly,

## Skills

HTML, CSS, JavaScript.
## Possible mentors

[Akshat Sharma](https://github.com/akshatcoder-hash)

## Expected project size

1 hours.

## Difficulty

Easy

**Comment by GJS2162** [comment]
> # #329
> ### I have learned basics of HTML and CSS
> ### Problem : Background and Template
> ### 9 - 15 September
@akshatcoder-hash

**Comment by Ujjwal-soni98** [comment]
PROBLEM: improve the BACKGROUND OF WEBSITE .
I currently deal with front-end section of the websites.I have good idea about HTML and CSS also a handful of knowledge about javascript.learning phase in javascript and seeking to learn back-end and then i will dive into the full-stack development of websites.

I will try to solve this issue sooner possible.
I wil first change the website's background so that it look decent and make it responsive.
@akshatcoder-hash

**Comment by adityyaa-10** [comment]
Redesign the background of the website

## About me 
I am Aditya Pandey, I am learning web development for like more than one and a half months. I have had my hands dirty on HTML, CSS and Javascript, till now.
Apart from that, I know C and C++ as well. 

## Issue
Redesign the background of the website

## Proposal
To redesign background of website 

## Timeline
11th September - 12th September

## Commitments
I'll try to submit it as soon as possible.

**Comment by manaswii** [comment]
# Update Readme
### Background and Technical Skills.
Knowledge and experience in C++, C, python, flask, SQL, some basic HTML, CSS and JavaScript.
### Proposed Solution
- Fix the colours and visibility of the website
- Make the website responsive
### queries
can I use bootstrap to make the website responsive? 
### Timeline to solve the problem.
### Sept 13 - Sept 17

**Comment by manaswii** [comment]
# Redesign background
### Background and Technical Skills.
Knowledge and experience in C++, C, python, flask, SQL, some basic HTML, CSS and JavaScript.
### Proposed Solution
- Fix the colours and visibility of the website
- Make the website responsive
### Queries
- can I use bootstrap to make the website responsive? 
- Would you prefer a dark or a bright background?
### Timeline to solve the problem.
### Sept 13 - Sept 17

**Comment by Ujjwal-soni98** [comment]
@akshatcoder-hash I have made the pull request making changes regarding the issue assigned . Kindly review it!

**Comment by akshatcoder-hash** [comment]
Great work @Ujjwal-soni98!
